import { db } from '@/db';
import { foodItems } from '@/db/schema';

async function main() {
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

    const sampleFoodItems = [
        // BREAKFAST (8 items)
        {
            name: 'Idli',
            description: 'Soft steamed rice cakes',
            category: 'BREAKFAST',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Dosa',
            description: 'Crispy rice crepe',
            category: 'BREAKFAST',
            price: 30,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 15,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Vada',
            description: 'Crispy lentil donuts',
            category: 'BREAKFAST',
            price: 15,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Pongal',
            description: 'Savory rice and lentil dish',
            category: 'BREAKFAST',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 15,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Upma',
            description: 'Semolina breakfast dish',
            category: 'BREAKFAST',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Parotta',
            description: 'Flaky layered flatbread',
            category: 'BREAKFAST',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 12,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Poori',
            description: 'Deep fried puffed bread with potato curry',
            category: 'BREAKFAST',
            price: 30,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 15,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Bread Omelette',
            description: 'Omelette with bread slices',
            category: 'BREAKFAST',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 8,
            createdAt: sevenDaysAgo,
        },
        // LUNCH (7 items)
        {
            name: 'Meals',
            description: 'Complete South Indian thali with rice, sambar, rasam, vegetables',
            category: 'LUNCH',
            price: 60,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 20,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Sambar Rice',
            description: 'Rice mixed with sambar',
            category: 'LUNCH',
            price: 40,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 15,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Curd Rice',
            description: 'Rice with yogurt and tempering',
            category: 'LUNCH',
            price: 30,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Biriyani',
            description: 'Aromatic rice with spices and vegetables',
            category: 'LUNCH',
            price: 80,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 30,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Fried Rice',
            description: 'Indo-Chinese style fried rice',
            category: 'LUNCH',
            price: 70,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 20,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Parotta with Kurma',
            description: 'Parotta served with vegetable kurma',
            category: 'LUNCH',
            price: 50,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 18,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Chappati',
            description: 'Whole wheat flatbread with curry',
            category: 'LUNCH',
            price: 40,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 15,
            createdAt: sevenDaysAgo,
        },
        // SNACKS (8 items)
        {
            name: 'Samosa',
            description: 'Crispy pastry with potato filling',
            category: 'SNACKS',
            price: 15,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Bajji',
            description: 'Batter fried vegetables',
            category: 'SNACKS',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 8,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Bonda',
            description: 'Spicy potato fritters',
            category: 'SNACKS',
            price: 15,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 8,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Cutlet',
            description: 'Vegetable cutlet',
            category: 'SNACKS',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Sandwich',
            description: 'Vegetable grilled sandwich',
            category: 'SNACKS',
            price: 35,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Puff',
            description: 'Flaky pastry with filling',
            category: 'SNACKS',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Vadai',
            description: 'Lentil fritters',
            category: 'SNACKS',
            price: 10,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 8,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Pakoda',
            description: 'Mixed vegetable fritters',
            category: 'SNACKS',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 10,
            createdAt: sevenDaysAgo,
        },
        // BEVERAGES (8 items)
        {
            name: 'Tea',
            description: 'Hot Indian chai',
            category: 'BEVERAGES',
            price: 10,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Coffee',
            description: 'Filter coffee',
            category: 'BEVERAGES',
            price: 15,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Lemon Juice',
            description: 'Fresh lemon juice',
            category: 'BEVERAGES',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 3,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Badam Milk',
            description: 'Almond flavored milk',
            category: 'BEVERAGES',
            price: 30,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Boost',
            description: 'Chocolate health drink',
            category: 'BEVERAGES',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 3,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Horlicks',
            description: 'Malted health drink',
            category: 'BEVERAGES',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 3,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Cool Drinks',
            description: 'Carbonated soft drinks',
            category: 'BEVERAGES',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 1,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Buttermilk',
            description: 'Spiced yogurt drink',
            category: 'BEVERAGES',
            price: 15,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 3,
            createdAt: sevenDaysAgo,
        },
        // DESSERT (5 items)
        {
            name: 'Ice Cream',
            description: 'Assorted flavors',
            category: 'DESSERT',
            price: 30,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 2,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Payasam',
            description: 'Sweet rice pudding',
            category: 'DESSERT',
            price: 25,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Gulab Jamun',
            description: 'Sweet milk dumplings in syrup',
            category: 'DESSERT',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 3,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Jigarthanda',
            description: 'Madurai special cold drink',
            category: 'DESSERT',
            price: 40,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Falooda',
            description: 'Rose flavored dessert drink',
            category: 'DESSERT',
            price: 50,
            imageUrl: null,
            isAvailable: true,
            isCombo: false,
            comboItems: null,
            preparationTime: 5,
            createdAt: sevenDaysAgo,
        },
        // COMBO OFFERS (4 items)
        {
            name: 'Breakfast Combo',
            description: 'Idli + Vada + Coffee',
            category: 'COMBO OFFERS',
            price: 50,
            imageUrl: null,
            isAvailable: true,
            isCombo: true,
            comboItems: [1, 3, 25],
            preparationTime: 15,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Lunch Special',
            description: 'Meals + Buttermilk',
            category: 'COMBO OFFERS',
            price: 70,
            imageUrl: null,
            isAvailable: true,
            isCombo: true,
            comboItems: [9, 31],
            preparationTime: 20,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Evening Snack Combo',
            description: 'Samosa + Tea',
            category: 'COMBO OFFERS',
            price: 20,
            imageUrl: null,
            isAvailable: true,
            isCombo: true,
            comboItems: [16, 24],
            preparationTime: 8,
            createdAt: sevenDaysAgo,
        },
        {
            name: 'Student Special',
            description: 'Biriyani + Cool Drink',
            category: 'COMBO OFFERS',
            price: 90,
            imageUrl: null,
            isAvailable: true,
            isCombo: true,
            comboItems: [12, 30],
            preparationTime: 30,
            createdAt: sevenDaysAgo,
        },
    ];

    await db.insert(foodItems).values(sampleFoodItems);
    
    console.log('✅ Food items seeder completed successfully - 40 items added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});